const $=id=>document.getElementById(id);
const state=JSON.parse(localStorage.getItem("beastStudio")||"{}");
const defaultApi=state.apiUrl||"";
$("apiUrl").value=defaultApi;

document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{
  document.querySelectorAll(".tab,.tabpage").forEach(x=>x.classList.remove("active"));
  b.classList.add("active"); $(b.dataset.tab).classList.add("active");
});

function save(){
  state.universeName=$("universeName").value;
  state.bible=$("bible").value;
  state.apiUrl=$("apiUrl").value.trim();
  localStorage.setItem("beastStudio",JSON.stringify(state));
}
$("saveUniverse").onclick=()=>{save(); alert("Universe saved on this device.");};
$("saveSettings").onclick=()=>{save(); alert("Settings saved.");};

$("demoBtn").onclick=()=>{
  $("universeName").value="Beastbound Legends";
  $("bible").value="An original fantasy world where young beast friends explore a hidden forest. Their childhood adventures slowly reveal dragons, an ancient symbol, rival clans and a mysterious villain. As they grow, the story moves from fun discoveries to training, daring chases and a large ancient conflict.";
  save(); alert("Demo universe loaded.");
};

$("generateChapter").onclick=()=>{
  const n=$("chapterNo").value||1, stage=$("stage").value;
  const ideas={
    "Childhood — fun & discovery":["Race Through the Forest","Baby Dragon","Festival of Beasts","Forbidden Cave"],
    "Growing up — training & mystery":["First Real Mission","Lost Dragon","Shadow Villain","Secret of the Ancient City"],
    "Teen years — missions & danger":["Dragon Chase","Villain's Trap","Escape Across the Sky Bridge","The Broken Promise"],
    "Adult — daring chases & major conflict":["Ancient Beast Awakens","Great Kingdom Chase","Dragon War Begins","Final Hunt"]
  };
  const arr=ideas[stage]||ideas["Childhood — fun & discovery"];
  const title=arr[(Number(n)-1)%arr.length];
  $("chapterOutput").textContent=`Chapter ${n}: ${title}\n\nStage: ${stage}\n\nScene 1 — Setup\nScene 2 — Discovery\nScene 3 — Chase / challenge\nScene 4 — Mystery reveal\nScene 5 — Cliffhanger\n\nHindi narration/dialogue can be generated by the cloud AI endpoint when connected.`;
};

function renderQueue(){
  const q=JSON.parse(localStorage.getItem("beastQueue")||"[]");
  $("queue").innerHTML=q.length?q.map((x,i)=>`<div class="item"><span>${i+1}. ${x.title}</span><small>${x.type} • ${x.status}</small></div>`).join(""):"No jobs yet.";
}
$("makePlan").onclick=()=>{
  const q=[];
  for(let i=1;i<=4;i++)q.push({title:`Short ${i} — chapter moment`,type:"Short",status:"planned"});
  for(let i=1;i<=2;i++)q.push({title:`Long Video ${i} — chapter`,type:"Long",status:"planned"});
  localStorage.setItem("beastQueue",JSON.stringify(q));renderQueue();
};

$("seoBtn").onclick=()=>{
  const t=$("seoTopic").value||"Beast anime adventure";
  $("seoOutput").textContent=`Title: ${t} | Beast Anime Adventure\n\nDescription: An original Hindi fantasy anime chapter featuring beasts, mystery and an ancient secret.\n\nTags: #anime #beastanime #hindianime #fantasy #dragon #animeShorts`;
};

$("checkBackend").onclick=async()=>{
  const url=$("apiUrl").value.trim();
  if(!url){$("backendStatus").textContent="Add your cloud API URL in Settings.";return}
  try{const r=await fetch(url.replace(/\/$/,"")+"/health"); const d=await r.json(); $("backendStatus").textContent=`Backend online: ${d.status||"ok"}`;$("backendStatus").className="status ok";}
  catch(e){$("backendStatus").textContent="Could not reach backend. Check the URL and deployment.";}
};
$("openBackend").onclick=()=>{const u=$("apiUrl").value.trim(); if(u) location.href=u+"/docs"; else alert("Set the backend URL first.");};

if("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js").catch(()=>{});
window.addEventListener("load",()=>{if(state.universeName)$("universeName").value=state.universeName;if(state.bible)$("bible").value=state.bible;renderQueue();});
